$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1419762776625.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"VarNum",
"VarXuehao"],
  "page":{
    "packageId":"e0c999c43ebb440aa1960e29b7ff5cd6",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2b167e0a6c84404fbf54d8f660743989",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":30,
              "y":111},
            "size":{
              "width":180,
              "height":389}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee6a92f1cb7b4b6eafae40559cfde7f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":30,
                  "y":111},
                "size":{
                  "width":180,
                  "height":389}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"f4756c1049fd4d8daa27d30f0dcf6ca1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":160},
            "size":{
              "width":670,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e13937298a41ecab40cd40b7d7b7b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d7b8cdd95d84e128c0e932b4a18aea0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u3.png"}},
{
              "id":"6a049dd3141c4a6187f7e259efc4cec7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eab6dfd391714ca49fc27a17051c05ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u3.png"}},
{
              "id":"616beead77ae455eb7f5e7aa2184fb17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"056a70fecd7d43b488c13caa761af904",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u7.png"}},
{
              "id":"17f94ff47a714a1b8206c130e10e4fa4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":320,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3eacc336b3bf4677b7a84ecfecb245f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":320,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u3.png"}},
{
              "id":"6096c86638ac4a18b304486f9372ff96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":520,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ee17cb5f6a44aa28b20162ea81a1617",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u13.png"}},
{
              "id":"e1bb454efb334e7aafae13beadae757e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":420,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"505f8ba803b44289aa52607d53c2f8e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u3.png"}}]},
{
          "id":"f43bca178ab046ed83476415660f6972",
          "label":"list",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":190},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on num equal to &quot;[[item.num]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9756447a0dca427a8242f7d0f6029f47"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.num]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"num",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on xuehao equal to &quot;[[item.xuehao]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b81302b358d24650aef2d9d76c841732"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.xuehao]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"xuehao",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on name equal to &quot;[[item.name]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7051b95ad4ab46ebafad0bc9361d02de"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.name]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"name",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on age equal to &quot;[[item.age]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["5bd299c2213b43f4a2bb69171516579e"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.age]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"age",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on sex equal to &quot;[[item.sex]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["518ccedb182c45da91bdb84a6e4726d1"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.sex]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"sex",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on phone equal to &quot;[[item.phone]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["51094d4b92ed446f80419b60332707e3"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.phone]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"phone",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":670,
              "height":29,
              "loadLocalDefault":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":true,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":242,
                "g":242,
                "b":242,
                "a":1}}},
          "objects":[{
              "id":"1580223851424d75a587ef5c72fb35e6",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":670,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2451946dcd5493cbeaa6dcd2d036dc9",
                  "label":"num",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9756447a0dca427a8242f7d0f6029f47",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/num_u17.png"}},
{
                  "id":"6aa684b1bd00481a944e632a0aa2c880",
                  "label":"xuehao",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b81302b358d24650aef2d9d76c841732",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/num_u17.png"}},
{
                  "id":"e05e87cd28914a8c8fc1fdfa156c8a43",
                  "label":"name",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7051b95ad4ab46ebafad0bc9361d02de",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":120,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/name_u21.png"}},
{
                  "id":"d1da707e89004bf98fef36752cc955b4",
                  "label":"age",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":320,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bd299c2213b43f4a2bb69171516579e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":320,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/num_u17.png"}},
{
                  "id":"5a98fcfe26d0437d8ff7c9be1659d80f",
                  "label":"phone",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51094d4b92ed446f80419b60332707e3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":520,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/phone_u27.png"}},
{
                  "id":"4d1fca0968a74fffa2a06616044287c3",
                  "label":"sex",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"518ccedb182c45da91bdb84a6e4726d1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":420,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/num_u17.png"}}]}],
          "data":[{
              "num":{
                "type":"text",
                "text":"1"},
              "xuehao":{
                "type":"text",
                "text":"23"},
              "name":{
                "type":"text",
                "text":"白玉芬"},
              "age":{
                "type":"text",
                "text":"23"},
              "sex":{
                "type":"text",
                "text":"女"},
              "email":{
                "type":"text",
                "text":"baiyufen@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000001"}},
{
              "num":{
                "type":"text",
                "text":"2"},
              "xuehao":{
                "type":"text",
                "text":"29"},
              "name":{
                "type":"text",
                "text":"仓春莲"},
              "age":{
                "type":"text",
                "text":"21"},
              "sex":{
                "type":"text",
                "text":"女"},
              "email":{
                "type":"text",
                "text":"cangchunlian@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000002"}},
{
              "num":{
                "type":"text",
                "text":"3"},
              "xuehao":{
                "type":"text",
                "text":"33"},
              "name":{
                "type":"text",
                "text":"陈国祥"},
              "age":{
                "type":"text",
                "text":"25"},
              "sex":{
                "type":"text",
                "text":"男"},
              "email":{
                "type":"text",
                "text":"chenguoxiang@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000003"}},
{
              "num":{
                "type":"text",
                "text":"4"},
              "xuehao":{
                "type":"text",
                "text":"34"},
              "name":{
                "type":"text",
                "text":"邓海燕"},
              "age":{
                "type":"text",
                "text":"23"},
              "sex":{
                "type":"text",
                "text":"女"},
              "email":{
                "type":"text",
                "text":"zhenghaiyan@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000004"}},
{
              "num":{
                "type":"text",
                "text":"5"},
              "xuehao":{
                "type":"text",
                "text":"38"},
              "name":{
                "type":"text",
                "text":"范惠"},
              "age":{
                "type":"text",
                "text":"24"},
              "sex":{
                "type":"text",
                "text":"女"},
              "email":{
                "type":"text",
                "text":"fanhui@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000005"}},
{
              "num":{
                "type":"text",
                "text":"6"},
              "xuehao":{
                "type":"text",
                "text":"41"},
              "name":{
                "type":"text",
                "text":"束长元"},
              "age":{
                "type":"text",
                "text":"26"},
              "sex":{
                "type":"text",
                "text":"男"},
              "email":{
                "type":"text",
                "text":"shuchangyuan@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000006"}},
{
              "num":{
                "type":"text",
                "text":"7"},
              "xuehao":{
                "type":"text",
                "text":"47"},
              "name":{
                "type":"text",
                "text":"明汉琴"},
              "age":{
                "type":"text",
                "text":"21"},
              "sex":{
                "type":"text",
                "text":"男"},
              "email":{
                "type":"text",
                "text":"minghanqin@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000007"}}],
          "dataProps":["num",
"xuehao",
"name",
"age",
"sex",
"email",
"phone"]},
{
          "id":"442f0b79ac1149179a07668ceb104504",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":606,
              "y":112.5},
            "size":{
              "width":110,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"Case 1<br> (If selected option of This equals &quot;全部&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"全部",
                      "stos":[]}},
                  "actions":[{
                      "action":"removeFilterFromRepeater",
                      "description":"Remove Filter filter_sex from list",
                      "repeatersToRemoveFilter":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "removeAll":false,
                          "filterName":"filter_sex"}]}]},
{
                  "description":"Case 2<br> (Else If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"addFilterToRepeater",
                      "description":"Add Filter filter_sex to list",
                      "repeatersToAddFilter":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "label":"filter_sex",
                          "filter":{
                            "exprType":"stringLiteral",
                            "value":"[[Item.sex == LVAR1]]",
                            "localVariables":{
                              "lvar1":{
                                "exprType":"fcall",
                                "functionName":"GetSelectedOption",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":true,
                                    "isFocused":false,
                                    "isTarget":false}]}},
                            "stos":[{
                                "computedType":"boolean",
                                "sto":"binOp",
                                "op":"==",
                                "leftSTO":{
                                  "sto":"item",
                                  "name":"sex",
                                  "isTarget":false},
                                "rightSTO":{
                                  "sto":"var",
                                  "name":"lvar1"}}]}}]}]}]}}},
{
          "id":"67cd0f05301a4a6b8cc75558c950ea28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":563,
              "y":116},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b53941c782b04e8c9e359379521b04bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":563,
                  "y":116},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0dcc2afb50343548653c540db77b7dd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":112.5},
            "size":{
              "width":110,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"Case 1<br> (If selected option of This equals &quot;全部&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"全部",
                      "stos":[]}},
                  "actions":[{
                      "action":"removeFilterFromRepeater",
                      "description":"Remove Filter filter_num from list",
                      "repeatersToRemoveFilter":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "removeAll":false,
                          "filterName":"filter_num"}]},
{
                      "action":"removeFilterFromRepeater",
                      "description":"Remove Filter filter_num_2 from list",
                      "repeatersToRemoveFilter":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "removeAll":false,
                          "filterName":"filter_num_2"}]}]},
{
                  "description":"Case 2<br> (Else If selected option of This equals &quot;1-3&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"1-3",
                      "stos":[]}},
                  "actions":[{
                      "action":"removeFilterFromRepeater",
                      "description":"Remove Filter filter_num_2 from list",
                      "repeatersToRemoveFilter":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "removeAll":false,
                          "filterName":"filter_num_2"}]},
{
                      "action":"addFilterToRepeater",
                      "description":"Add Filter filter_num to list",
                      "repeatersToAddFilter":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "label":"filter_num",
                          "filter":{
                            "exprType":"stringLiteral",
                            "value":"[[Item.num<=3  ]]",
                            "localVariables":{
},
                            "stos":[{
                                "computedType":"boolean",
                                "sto":"binOp",
                                "op":"<=",
                                "leftSTO":{
                                  "sto":"item",
                                  "name":"num",
                                  "isTarget":false},
                                "rightSTO":{
                                  "computedType":"int",
                                  "sto":"literal",
                                  "value":3}}]}}]}]},
{
                  "description":"Case 3<br> (Else If selected option of This equals &quot;4-7&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"4-7",
                      "stos":[]}},
                  "actions":[{
                      "action":"removeFilterFromRepeater",
                      "description":"Remove Filter filter_num from list",
                      "repeatersToRemoveFilter":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "removeAll":false,
                          "filterName":"filter_num"}]},
{
                      "action":"addFilterToRepeater",
                      "description":"Add Filter filter_num_2 to list",
                      "repeatersToAddFilter":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "label":"filter_num_2",
                          "filter":{
                            "exprType":"stringLiteral",
                            "value":"[[Item.num >= 4 && item.num <=7 ]]",
                            "localVariables":{
},
                            "stos":[{
                                "computedType":"boolean",
                                "sto":"binOp",
                                "op":"&&",
                                "leftSTO":{
                                  "computedType":"boolean",
                                  "sto":"binOp",
                                  "op":">=",
                                  "leftSTO":{
                                    "sto":"item",
                                    "name":"num",
                                    "isTarget":false},
                                  "rightSTO":{
                                    "computedType":"int",
                                    "sto":"literal",
                                    "value":4}},
                                "rightSTO":{
                                  "computedType":"boolean",
                                  "sto":"binOp",
                                  "op":"<=",
                                  "leftSTO":{
                                    "sto":"item",
                                    "name":"num",
                                    "isTarget":false},
                                  "rightSTO":{
                                    "computedType":"int",
                                    "sto":"literal",
                                    "value":7}}}]}}]}]}]}}},
{
          "id":"09872eb941cc42b69e770b702adfc970",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":116},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c82c8737af844199aab696c9a5614a99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":116},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2b167e0a6c84404fbf54d8f660743989":{
      "scriptId":"u0"},
    "ee6a92f1cb7b4b6eafae40559cfde7f9":{
      "scriptId":"u1"},
    "f4756c1049fd4d8daa27d30f0dcf6ca1":{
      "scriptId":"u2"},
    "48e13937298a41ecab40cd40b7d7b7b5":{
      "scriptId":"u3"},
    "2d7b8cdd95d84e128c0e932b4a18aea0":{
      "scriptId":"u4"},
    "6a049dd3141c4a6187f7e259efc4cec7":{
      "scriptId":"u5"},
    "eab6dfd391714ca49fc27a17051c05ca":{
      "scriptId":"u6"},
    "616beead77ae455eb7f5e7aa2184fb17":{
      "scriptId":"u7"},
    "056a70fecd7d43b488c13caa761af904":{
      "scriptId":"u8"},
    "17f94ff47a714a1b8206c130e10e4fa4":{
      "scriptId":"u9"},
    "3eacc336b3bf4677b7a84ecfecb245f3":{
      "scriptId":"u10"},
    "e1bb454efb334e7aafae13beadae757e":{
      "scriptId":"u11"},
    "505f8ba803b44289aa52607d53c2f8e5":{
      "scriptId":"u12"},
    "6096c86638ac4a18b304486f9372ff96":{
      "scriptId":"u13"},
    "8ee17cb5f6a44aa28b20162ea81a1617":{
      "scriptId":"u14"},
    "f43bca178ab046ed83476415660f6972":{
      "scriptId":"u15"},
    "1580223851424d75a587ef5c72fb35e6":{
      "scriptId":"u16"},
    "e2451946dcd5493cbeaa6dcd2d036dc9":{
      "scriptId":"u17"},
    "9756447a0dca427a8242f7d0f6029f47":{
      "scriptId":"u18"},
    "6aa684b1bd00481a944e632a0aa2c880":{
      "scriptId":"u19"},
    "b81302b358d24650aef2d9d76c841732":{
      "scriptId":"u20"},
    "e05e87cd28914a8c8fc1fdfa156c8a43":{
      "scriptId":"u21"},
    "7051b95ad4ab46ebafad0bc9361d02de":{
      "scriptId":"u22"},
    "d1da707e89004bf98fef36752cc955b4":{
      "scriptId":"u23"},
    "5bd299c2213b43f4a2bb69171516579e":{
      "scriptId":"u24"},
    "4d1fca0968a74fffa2a06616044287c3":{
      "scriptId":"u25"},
    "518ccedb182c45da91bdb84a6e4726d1":{
      "scriptId":"u26"},
    "5a98fcfe26d0437d8ff7c9be1659d80f":{
      "scriptId":"u27"},
    "51094d4b92ed446f80419b60332707e3":{
      "scriptId":"u28"},
    "442f0b79ac1149179a07668ceb104504":{
      "scriptId":"u29"},
    "67cd0f05301a4a6b8cc75558c950ea28":{
      "scriptId":"u30"},
    "b53941c782b04e8c9e359379521b04bf":{
      "scriptId":"u31"},
    "c0dcc2afb50343548653c540db77b7dd":{
      "scriptId":"u32"},
    "09872eb941cc42b69e770b702adfc970":{
      "scriptId":"u33"},
    "c82c8737af844199aab696c9a5614a99":{
      "scriptId":"u34"}}});