$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1419762108360.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"VarNum",
"VarXuehao"],
  "page":{
    "packageId":"e0c999c43ebb440aa1960e29b7ff5cd6",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2b167e0a6c84404fbf54d8f660743989",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "location":{
              "x":30,
              "y":111},
            "size":{
              "width":180,
              "height":389}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee6a92f1cb7b4b6eafae40559cfde7f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "location":{
                  "x":30,
                  "y":111},
                "size":{
                  "width":180,
                  "height":389}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"f4756c1049fd4d8daa27d30f0dcf6ca1",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":160},
            "size":{
              "width":670,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e13937298a41ecab40cd40b7d7b7b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d7b8cdd95d84e128c0e932b4a18aea0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u3.png"}},
{
              "id":"6a049dd3141c4a6187f7e259efc4cec7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eab6dfd391714ca49fc27a17051c05ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u3.png"}},
{
              "id":"616beead77ae455eb7f5e7aa2184fb17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"056a70fecd7d43b488c13caa761af904",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u7.png"}},
{
              "id":"17f94ff47a714a1b8206c130e10e4fa4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":320,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3eacc336b3bf4677b7a84ecfecb245f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":320,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u3.png"}},
{
              "id":"6096c86638ac4a18b304486f9372ff96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":520,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ee17cb5f6a44aa28b20162ea81a1617",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u13.png"}},
{
              "id":"e1bb454efb334e7aafae13beadae757e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":420,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"505f8ba803b44289aa52607d53c2f8e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/home/u3.png"}}]},
{
          "id":"f43bca178ab046ed83476415660f6972",
          "label":"list",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":190},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on num equal to &quot;[[item.num]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9756447a0dca427a8242f7d0f6029f47"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.num]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"num",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on xuehao equal to &quot;[[item.xuehao]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b81302b358d24650aef2d9d76c841732"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.xuehao]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"xuehao",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on name equal to &quot;[[item.name]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7051b95ad4ab46ebafad0bc9361d02de"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.name]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"name",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on age equal to &quot;[[item.age]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["5bd299c2213b43f4a2bb69171516579e"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.age]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"age",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on sex equal to &quot;[[item.sex]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["518ccedb182c45da91bdb84a6e4726d1"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.sex]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"sex",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on phone equal to &quot;[[item.phone]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["51094d4b92ed446f80419b60332707e3"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[item.phone]]",
                                "stos":[{
                                    "sto":"item",
                                    "name":"phone",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":670,
              "height":29,
              "loadLocalDefault":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":true,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":242,
                "g":242,
                "b":242,
                "a":1}}},
          "objects":[{
              "id":"1580223851424d75a587ef5c72fb35e6",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-1},
                "size":{
                  "width":670,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2451946dcd5493cbeaa6dcd2d036dc9",
                  "label":"num",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9756447a0dca427a8242f7d0f6029f47",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/num_u17.png"}},
{
                  "id":"6aa684b1bd00481a944e632a0aa2c880",
                  "label":"xuehao",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b81302b358d24650aef2d9d76c841732",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/num_u17.png"}},
{
                  "id":"e05e87cd28914a8c8fc1fdfa156c8a43",
                  "label":"name",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":120,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7051b95ad4ab46ebafad0bc9361d02de",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":120,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/name_u21.png"}},
{
                  "id":"d1da707e89004bf98fef36752cc955b4",
                  "label":"age",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":320,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bd299c2213b43f4a2bb69171516579e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":320,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/num_u17.png"}},
{
                  "id":"5a98fcfe26d0437d8ff7c9be1659d80f",
                  "label":"phone",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":520,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51094d4b92ed446f80419b60332707e3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":520,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/phone_u27.png"}},
{
                  "id":"4d1fca0968a74fffa2a06616044287c3",
                  "label":"sex",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"518ccedb182c45da91bdb84a6e4726d1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":420,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/num_u17.png"}}]}],
          "data":[{
              "num":{
                "type":"text",
                "text":"1"},
              "xuehao":{
                "type":"text",
                "text":"23"},
              "name":{
                "type":"text",
                "text":"白玉芬"},
              "age":{
                "type":"text",
                "text":"23"},
              "sex":{
                "type":"text",
                "text":"女"},
              "email":{
                "type":"text",
                "text":"baiyufen@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000001"}},
{
              "num":{
                "type":"text",
                "text":"2"},
              "xuehao":{
                "type":"text",
                "text":"29"},
              "name":{
                "type":"text",
                "text":"仓春莲"},
              "age":{
                "type":"text",
                "text":"21"},
              "sex":{
                "type":"text",
                "text":"女"},
              "email":{
                "type":"text",
                "text":"cangchunlian@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000002"}},
{
              "num":{
                "type":"text",
                "text":"3"},
              "xuehao":{
                "type":"text",
                "text":"33"},
              "name":{
                "type":"text",
                "text":"陈国祥"},
              "age":{
                "type":"text",
                "text":"25"},
              "sex":{
                "type":"text",
                "text":"男"},
              "email":{
                "type":"text",
                "text":"chenguoxiang@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000003"}},
{
              "num":{
                "type":"text",
                "text":"4"},
              "xuehao":{
                "type":"text",
                "text":"34"},
              "name":{
                "type":"text",
                "text":"邓海燕"},
              "age":{
                "type":"text",
                "text":"23"},
              "sex":{
                "type":"text",
                "text":"女"},
              "email":{
                "type":"text",
                "text":"zhenghaiyan@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000004"}},
{
              "num":{
                "type":"text",
                "text":"5"},
              "xuehao":{
                "type":"text",
                "text":"38"},
              "name":{
                "type":"text",
                "text":"范惠"},
              "age":{
                "type":"text",
                "text":"24"},
              "sex":{
                "type":"text",
                "text":"女"},
              "email":{
                "type":"text",
                "text":"fanhui@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000005"}},
{
              "num":{
                "type":"text",
                "text":"6"},
              "xuehao":{
                "type":"text",
                "text":"41"},
              "name":{
                "type":"text",
                "text":"束长元"},
              "age":{
                "type":"text",
                "text":"26"},
              "sex":{
                "type":"text",
                "text":"男"},
              "email":{
                "type":"text",
                "text":"shuchangyuan@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000006"}},
{
              "num":{
                "type":"text",
                "text":"7"},
              "xuehao":{
                "type":"text",
                "text":"47"},
              "name":{
                "type":"text",
                "text":"明汉琴"},
              "age":{
                "type":"text",
                "text":"21"},
              "sex":{
                "type":"text",
                "text":"男"},
              "email":{
                "type":"text",
                "text":"minghanqin@163.com"},
              "phone":{
                "type":"text",
                "text":"13800000007"}}],
          "dataProps":["num",
"xuehao",
"name",
"age",
"sex",
"email",
"phone"]},
{
          "id":"fe3d88e682474950b6d2034bccb99327",
          "label":"next_xuehao",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":95},
            "size":{
              "width":50,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b75edd43cd946a392e53f7d20b597e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":95},
                "size":{
                  "width":50,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/next_xuehao_u29.png"}},
{
          "id":"03defe19b73a44d3bec4c6e8bd28fa3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":95},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"429dd3e03ba146a8819b988bf736f419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":95},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbfe3a220b214d50bb0ba7534220e0e0",
          "label":"input_name",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":90.5},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"546285c4d9e24ccfba816eaba5df82ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":95},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd4b068e34f74a2c92c1223a6a0fdf2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":95},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50e50cf413df4286940898a6ba52f5c3",
          "label":"input_age",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3e712a2f2b1b43c1bd5f654a6906c3bf",
          "label":"input_sex",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":127},
            "size":{
              "width":60,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b0a3fa8c2b0649e8815b523bdca92def",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":130},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efbbdebc8c3d4f48baf43c3111f8a1ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":130},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ba525cd470a482fa5e18598106b1f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":130},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aec7e1ccbe14cd7a8d4d75e9ff754ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":130},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"427744f8020642d08555f0e9ee57b321",
          "label":"input_phone",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":125.5},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3299a45d40384e03ad0ca4c369d54190",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":125},
            "size":{
              "width":80,
              "height":25},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c91c33ea71941e9a39a18facefb4489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":125},
                "size":{
                  "width":80,
                  "height":25},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"addItemsToDataSet",
                      "description":"Add Rows 1 to list",
                      "dataSetsToAddTo":[{
                          "path":["f43bca178ab046ed83476415660f6972"],
                          "data":[{
                              "num":{
                                "type":"literal",
                                "text":"[[VarNum]]",
                                "literal":{
                                  "exprType":"stringLiteral",
                                  "value":"[[VarNum]]",
                                  "localVariables":{
},
                                  "stos":[{
                                      "sto":"var",
                                      "name":"varnum"}]}},
                              "xuehao":{
                                "type":"literal",
                                "text":"[[VarXuehao]]",
                                "literal":{
                                  "exprType":"stringLiteral",
                                  "value":"[[VarXuehao]]",
                                  "localVariables":{
},
                                  "stos":[{
                                      "sto":"var",
                                      "name":"varxuehao"}]}},
                              "name":{
                                "type":"literal",
                                "text":"[[LVAR1]]",
                                "literal":{
                                  "exprType":"stringLiteral",
                                  "value":"[[LVAR1]]",
                                  "localVariables":{
                                    "lvar1":{
                                      "exprType":"fcall",
                                      "functionName":"GetWidgetText",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["bbfe3a220b214d50bb0ba7534220e0e0"]}]}},
                                  "stos":[{
                                      "sto":"var",
                                      "name":"lvar1"}]}},
                              "age":{
                                "type":"literal",
                                "text":"[[LVAR1]]",
                                "literal":{
                                  "exprType":"stringLiteral",
                                  "value":"[[LVAR1]]",
                                  "localVariables":{
                                    "lvar1":{
                                      "exprType":"fcall",
                                      "functionName":"GetWidgetText",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["50e50cf413df4286940898a6ba52f5c3"]}]}},
                                  "stos":[{
                                      "sto":"var",
                                      "name":"lvar1"}]}},
                              "sex":{
                                "type":"literal",
                                "text":"[[LVAR1]]",
                                "literal":{
                                  "exprType":"stringLiteral",
                                  "value":"[[LVAR1]]",
                                  "localVariables":{
                                    "lvar1":{
                                      "exprType":"fcall",
                                      "functionName":"GetSelectedOption",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["3e712a2f2b1b43c1bd5f654a6906c3bf"]}]}},
                                  "stos":[{
                                      "sto":"var",
                                      "name":"lvar1"}]}},
                              "phone":{
                                "type":"literal",
                                "text":"[[LVAR1]]",
                                "literal":{
                                  "exprType":"stringLiteral",
                                  "value":"[[LVAR1]]",
                                  "localVariables":{
                                    "lvar1":{
                                      "exprType":"fcall",
                                      "functionName":"GetWidgetText",
                                      "arguments":[{
                                          "exprType":"pathLiteral",
                                          "isThis":false,
                                          "isFocused":false,
                                          "isTarget":false,
                                          "value":["427744f8020642d08555f0e9ee57b321"]}]}},
                                  "stos":[{
                                      "sto":"var",
                                      "name":"lvar1"}]}}}]}]},
{
                      "action":"setFunction",
                      "description":"Set value of VarNum equal to &quot;[[VarNum+1]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"VarNum"},
{
                                "exprType":"stringLiteral",
                                "value":"[[VarNum+1]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "sto":"var",
                                      "name":"varnum"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":1}}]}]}]}},
{
                      "action":"setFunction",
                      "description":"Set value of VarXuehao equal to &quot;[[VarXuehao+1]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"VarXuehao"},
{
                                "exprType":"stringLiteral",
                                "value":"[[VarXuehao+1]]",
                                "stos":[{
                                    "computedType":"int",
                                    "sto":"binOp",
                                    "op":"+",
                                    "leftSTO":{
                                      "sto":"var",
                                      "name":"varxuehao"},
                                    "rightSTO":{
                                      "computedType":"int",
                                      "sto":"literal",
                                      "value":1}}]}]}]}},
{
                      "action":"setFunction",
                      "description":"Set text on next_xuehao equal to value of VarXuehao",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["4b75edd43cd946a392e53f7d20b597e2"]},
{
                                "exprType":"fcall",
                                "functionName":"GetGlobalVariableValue",
                                "arguments":[{
                                    "exprType":"globalVariableLiteral",
                                    "variableName":"VarXuehao"}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u43.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2b167e0a6c84404fbf54d8f660743989":{
      "scriptId":"u0"},
    "ee6a92f1cb7b4b6eafae40559cfde7f9":{
      "scriptId":"u1"},
    "f4756c1049fd4d8daa27d30f0dcf6ca1":{
      "scriptId":"u2"},
    "48e13937298a41ecab40cd40b7d7b7b5":{
      "scriptId":"u3"},
    "2d7b8cdd95d84e128c0e932b4a18aea0":{
      "scriptId":"u4"},
    "6a049dd3141c4a6187f7e259efc4cec7":{
      "scriptId":"u5"},
    "eab6dfd391714ca49fc27a17051c05ca":{
      "scriptId":"u6"},
    "616beead77ae455eb7f5e7aa2184fb17":{
      "scriptId":"u7"},
    "056a70fecd7d43b488c13caa761af904":{
      "scriptId":"u8"},
    "17f94ff47a714a1b8206c130e10e4fa4":{
      "scriptId":"u9"},
    "3eacc336b3bf4677b7a84ecfecb245f3":{
      "scriptId":"u10"},
    "e1bb454efb334e7aafae13beadae757e":{
      "scriptId":"u11"},
    "505f8ba803b44289aa52607d53c2f8e5":{
      "scriptId":"u12"},
    "6096c86638ac4a18b304486f9372ff96":{
      "scriptId":"u13"},
    "8ee17cb5f6a44aa28b20162ea81a1617":{
      "scriptId":"u14"},
    "f43bca178ab046ed83476415660f6972":{
      "scriptId":"u15"},
    "1580223851424d75a587ef5c72fb35e6":{
      "scriptId":"u16"},
    "e2451946dcd5493cbeaa6dcd2d036dc9":{
      "scriptId":"u17"},
    "9756447a0dca427a8242f7d0f6029f47":{
      "scriptId":"u18"},
    "6aa684b1bd00481a944e632a0aa2c880":{
      "scriptId":"u19"},
    "b81302b358d24650aef2d9d76c841732":{
      "scriptId":"u20"},
    "e05e87cd28914a8c8fc1fdfa156c8a43":{
      "scriptId":"u21"},
    "7051b95ad4ab46ebafad0bc9361d02de":{
      "scriptId":"u22"},
    "d1da707e89004bf98fef36752cc955b4":{
      "scriptId":"u23"},
    "5bd299c2213b43f4a2bb69171516579e":{
      "scriptId":"u24"},
    "4d1fca0968a74fffa2a06616044287c3":{
      "scriptId":"u25"},
    "518ccedb182c45da91bdb84a6e4726d1":{
      "scriptId":"u26"},
    "5a98fcfe26d0437d8ff7c9be1659d80f":{
      "scriptId":"u27"},
    "51094d4b92ed446f80419b60332707e3":{
      "scriptId":"u28"},
    "fe3d88e682474950b6d2034bccb99327":{
      "scriptId":"u29"},
    "4b75edd43cd946a392e53f7d20b597e2":{
      "scriptId":"u30"},
    "03defe19b73a44d3bec4c6e8bd28fa3a":{
      "scriptId":"u31"},
    "429dd3e03ba146a8819b988bf736f419":{
      "scriptId":"u32"},
    "bbfe3a220b214d50bb0ba7534220e0e0":{
      "scriptId":"u33"},
    "546285c4d9e24ccfba816eaba5df82ae":{
      "scriptId":"u34"},
    "fd4b068e34f74a2c92c1223a6a0fdf2b":{
      "scriptId":"u35"},
    "50e50cf413df4286940898a6ba52f5c3":{
      "scriptId":"u36"},
    "3e712a2f2b1b43c1bd5f654a6906c3bf":{
      "scriptId":"u37"},
    "b0a3fa8c2b0649e8815b523bdca92def":{
      "scriptId":"u38"},
    "efbbdebc8c3d4f48baf43c3111f8a1ca":{
      "scriptId":"u39"},
    "3ba525cd470a482fa5e18598106b1f50":{
      "scriptId":"u40"},
    "2aec7e1ccbe14cd7a8d4d75e9ff754ff":{
      "scriptId":"u41"},
    "427744f8020642d08555f0e9ee57b321":{
      "scriptId":"u42"},
    "3299a45d40384e03ad0ca4c369d54190":{
      "scriptId":"u43"},
    "2c91c33ea71941e9a39a18facefb4489":{
      "scriptId":"u44"}}});